### ISSUE TITLE
Stylesheets for Bibl

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus-app#126]
@wsalesky The style sheet for the source on http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/100 is missing the period at the end of the citation.

See http://wwwb.library.vanderbilt.edu/bibl/2491 where the preferred citation has a period at the end.

Also, separately, we need to write a test so that Syriac Characters are never italicized in these style-sheets. Would that be possible please?

**Comment by wsalesky** [comment]
Fixed.

**Comment by wsalesky** [comment]
@davidamichelson In order to control the output of the Syriac, it has to be wrapped in `tei:foreign/@xml:lang`

ex: 
```
<title level="m">The New Testament in Syriac [<foreign xml:lang="syr">ܕܝܬܝܩܐ ܚܕܬܐ ܕܡܪܢ ܝܫܘܥ  ܡܫܝܚܐ</foreign>]</title>
```

**Comment by jedwardwalters** [comment]
@davidamichelson and @wsalesky I added the xml:lang tag to the title element across all the NT documents (along with some other revisions). The Syriac is still showing up in italics though. See:
http://wwwb.library.vanderbilt.edu/exist/apps/syriac-corpus/100.html

**Comment by wsalesky** [comment]
@davidamichelson @jedwardwalters I think this is fixed. Reopen if not.
