### ISSUE TITLE
Coding of Syriac text at various points on the page

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriac-corpus-app#131]
@jedwardwalters wrote: @wsalesky I have a question I've been meaning to ask for a while: the Syriac text that shows up in the titles in these boxes looks different on different pages. Is there a coding thing on my end that's making this happen?

I saw this happening on my laptop and think it is due to some Syriac text not being fully tagged. We can show you in our meeting.

**Comment by jedwardwalters** [comment]
I just ran a find and replace across the corpus that looked for the `<foreign>` tag without the xml:lang attribute and added it. There were about 60 files that it corrected.

**Comment by wsalesky** [comment]
@davidamichelson @jedwardwalters Can this be closed? Or is there an action item for me? I think the titles in italics is a different issue: https://github.com/srophe/syriac-corpus-app/issues/126

**Comment by jedwardwalters** [comment]
This should be fixed now. If we run across any specific instances of the Syriac text not looking right, we can create a new issue.

**Comment by davidamichelson** [comment]
It seems to be still showing the behavior which is that Syriac text in the title of the work at the top is not being forced by the CSS into the prefered font. See this image.
![screenshot 2018-05-04 23 04 48](https://user-images.githubusercontent.com/3083773/39659528-cd57d874-4fef-11e8-8707-81a687711244.png)

**Comment by wsalesky** [comment]
@davidamichelson I think this is now fixed. Reopen if not.

**Comment by wsalesky** [comment]
Resolved in the Page title as well as the citations.
